%YAML 1.1
# SPDX-License-Identifier: MIT
# Copyright © 2019 André Santos
---
name: haros_plugin_pbt_gen
version: 0.4.0
languages:
    - cpp
    - python
rules:
    pbtest:
        name:           Property-based Test
        scope:          file
        description:    An automatic property-based test failed.
        tags:
            - testing
            - pbt
